name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Lint JS
        run: npm run lint:js

      - name: Install web-ext
        run: npm install -g web-ext

      - name: Lint extension
        run: web-ext lint --source-dir .